apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    generation: 1
  labels:
    app: todo-app
  name: todo-app
  namespace: default
 
  uid: e6aa7e16-3a59-4d26-a6f9-c0d2aeb38adb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: todo-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      
      labels:
        app: todo-app
    spec:
      containers:
      - image: swapnilsrd/vprofilecicd
        imagePullPolicy: Always
        name: vprofilecicd
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
