apiVersion: v1
kind: Service
metadata:
   labels:
    app: todo-app
  name: todo-app
  namespace: default
spec:
  ports:
  - nodePort: 31466
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: todo-app
  type: NodePort
status:
  loadBalancer: {}
