apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: todo-app
  name: todo-app
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: todo-app
  type: NodePort
status:
  loadBalancer: {}
