apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-09-26T16:57:50Z"
  labels:
    app: todo-app
  name: todo-app
  namespace: default
  resourceVersion: "38297"
  uid: 082d6498-c9b2-4e67-880d-8150346ab135
spec:
  clusterIP: 10.103.31.33
  clusterIPs:
  - 10.103.31.33
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31466
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: todo-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
